### ISSUE TITLE
Metrics not parsable by Prometheus

### ISSUE THREAD

**Issue by clayroach** [devsisters/shardcake#122]
Prometheus metrics scraper fails to pick up any metrics from the pods - chokes on the `sharding.entities` metric type and the others.  Per [docs](https://prometheus.io/docs/concepts/data_model/#metric-names-and-labels):

```
Metric names may contain ASCII letters, digits, underscores, and colons. It must match the regex [a-zA-Z_:][a-zA-Z0-9_:]*.
```

Simple fix is to change to:
```
object Metrics {
  val shards: Gauge[Double]     = Metric.gauge("shardcake_shards")
  val entities: Gauge[Double]   = Metric.gauge("shardcake_entities")
  val singletons: Gauge[Double] = Metric.gauge("shardcake_singletons")
}
```

**Comment by clayroach** [comment]
Branch is ready if you want me to create a PR.

**Comment by ghostdogpr** [comment]
I actually fixed that in zio-metrics: https://github.com/zio/zio-metrics-connectors/releases/tag/v2.3.1 (we wanted to keep using dots because we expose to Datadog as well).

**Comment by clayroach** [comment]
Perfect, thx.  Will close and update zio metrics!
