### ISSUE TITLE
Replace zio-grpc-core with release version

### ISSUE THREAD

**Issue by Al-assad** [devsisters/shardcake#13]
Hi, I noticed that shardcake references a snapshot version of `zio-grpc-core` on https://github.com/devsisters/shardcake/blob/series/2.x/build.sbt#L6

I'm curious as to what the reason for this is, as snapshot versions are less convenient for regular sbt dependency imports. AFAIK `zio-grpc-core` already has a release version 0.6 that supports both scala 3/2.13/2.12, see [maven repository](https://mvnrepository.com/artifact/com.thesamet.scalapb.zio-grpc/zio-grpc-core_3/0.6.0-test4)

**Comment by ghostdogpr** [comment]
Yeah, I was mostly waiting for an official release, not sure what's better between a snapshot and a version named "0.6.0-test4" 😆
We could definitely change it, it looks like they point to the same commit.

**Comment by Al-assad** [comment]
Thanks for your reply, I would be happy to do this work if allowed, we've recently been working on a plan to replace akka-cluster-sharding with Shardcake

**Comment by ghostdogpr** [comment]
Sure, thank you!

**Comment by ghostdogpr** [comment]
Closed by https://github.com/devsisters/shardcake/pull/15
