### ISSUE TITLE
How to register an entity to only some specific pods

### ISSUE THREAD

**Issue by BaekGeunYoung** [devsisters/shardcake#130]
There is a main application which hosts entity A, B, C. And I made a specific entity D, and I want to make a separate application which hosts entity D only. I want this architecture to separate traffic regarding to entity D with usual traffic. How can I achieve this?

**Comment by ghostdogpr** [comment]
Are A, B, C, D entities or entity types? Not sure if you want to separate a particular ID (entity) or group of entities (entity type)?

**Comment by BaekGeunYoung** [comment]
I mean entity type.

**Comment by ghostdogpr** [comment]
So currently the Shard Manager does not support different "roles", so all entities go to all pods that have registered to the Shard Manager.

The workaround for that is to use a different Shard Manager instance for your specific entity type D, and have those special pods register to that Shard Manager instance. It works well as long as entity types are on completely separated pods.
