### ISSUE TITLE
Custom entityID to shardID calculation

### ISSUE THREAD

**Issue by svroonland** [devsisters/shardcake#14]
First of all, great library!

I've worked on a project where, using Kafka, the entity IDs were not uniformly distributed over the Kafka partitions. This could cause some skew when running close to maximum capacity. In shardcake, using the current algorithm of `shardId = abs(entityId.hashCode % numberOfShards) + 1`, the situation could arise where the entities are not evenly divided over the shards.

Would it be possible to supply a custom shardID calculation? I'm also looking into a use case where `shardId = int(entityId)`.

**Comment by ghostdogpr** [comment]
Ah, didn't think of this so far because our IDs are evenly distributed. We could definitely make it configurable.
Would that be global or per entity type?

**Comment by ghostdogpr** [comment]
> shardId = int(entityId)

You still need to apply `% numberOfShards + 1` there, right? (shard IDs are expected to be between 1 and the number of shards).

**Comment by svroonland** [comment]
Yeah, modulo nrShards + 1 indeed. I guess it would have to be per entity type.
