### ISSUE TITLE
log when Shard Manager is fully started

### ISSUE THREAD

**Issue by wonryool-kim** [devsisters/shardcake#19]
When start shard manager, we need a log that it is fully initialized.
Now, shard manager logs `Shard Manager loaded` when it makes `ShardManager.live`
But, after making `ShardManager.live`,  it makes api through `Server.run`.
So I'm confused if it's fully initialized.

**Comment by ghostdogpr** [comment]
As I remember, zio-http didn't have a hook for the that but maybe there is now. I will double check.

**Comment by wonryool-kim** [comment]
https://zio.github.io/zio-http/docs/v1.x/dsl/server/#start-a-zio-http-server-with-custom-configurations
Can we use the make method?

**Comment by wonryool-kim** [comment]
And we need a log that shard manager stop. I saw the redis release log and knew that the server was dead.

**Comment by ghostdogpr** [comment]
Yeah, sounds good!
