### ISSUE TITLE
[Feature request] Cluster stats

### ISSUE THREAD

**Issue by NeQuissimus** [devsisters/shardcake#27]
Consider adding support for reporting statistics such as the following:
- Number of active pods
- Number of entities
- Number of shards
- Number of register/unregister events
- Results of health checks
- Start and stop (and by extension runtime) times of rebalances

Having the above in something like StatsD or Prometheus would enable visualizing cluster size, status and health very easily.

**Comment by ghostdogpr** [comment]
Currently we expose:
- `ShardManager#getAssignments` gives you shard assignments, we could expose `getPods` as well
- `ShardManager#getShardingEvents` gives you a stream of assignments/unassignments events. We could add `register` and `unregister` there.
- `Sharding#getPods` gives you all pods with their addresses

Note that most of these metrics would be on the shard manager side (rebalances, register/unregister events, etc), but some would be on the pods side (mostly entities: the shard manager doesn't know about them).

**Comment by NeQuissimus** [comment]
`ZIO Metrics` should provide an easy interface to send these values to various backends such as DataDog or Prometheus.

**Comment by ghostdogpr** [comment]
ZIO Metrics integration done in https://github.com/devsisters/shardcake/pull/116
