### ISSUE TITLE
Helpers to know if an entity type is registered

### ISSUE THREAD

**Issue by ghostdogpr** [devsisters/shardcake#29]
- add `isEntityTypeRegistered` to `Sharding`
- a function that returns a stream of changes could be nice

**Comment by altostraus** [comment]
What could type signature of that function be?

**Comment by ghostdogpr** [comment]
a `ZStream` of a new sealed trait `ShardingRegistrationEvent` that could be `EntityRegistered(entityType: EntityType)` or `SingletonRegistered(name: String)`

**Comment by altostraus** [comment]
what are singletons for? how do they differ from entities?

**Comment by ghostdogpr** [comment]
> what are singletons for? how do they differ from entities?

When you want a background process to run only once in your whole cluster. Like a scheduler for example.

**Comment by altostraus** [comment]
I see, but why do they have to run only in a singleton node(node that holds shard 1 ?)? 
Can't they run on shards across cluster, just like entities? 
Sorry I am learning Shardcake internals.

**Comment by ghostdogpr** [comment]
This is for when you have a use case where you want something unique, when you don't want it to run on more than one node but it's not an "entity" and has no ID. The major difference is also that singletons are always running, unlike entities that just wake up when they receive a message and stop when they are inactive. It's basically a background job that's unique across all nodes. You don't need to worry about where it runs, you just know that there's always one running.

**Comment by altostraus** [comment]
Good learning, thank you!
But assuming that running many singletons in a single node takes a lot of performance overhead, wouldn't  it be nice to spread that load across cluster? It could be possible to manage unique IDs for singletons internally to treat them like internal entities. So in this case, original entities are there for serving outside clients while singletons(internal entities) are there for internal clients. Just my naive idea.

**Comment by ghostdogpr** [comment]
Yeah you're right. Since we only have very few singletons and they basically use no CPU, we went for this naïve implementation. But we could imagine one where the entityID is not hardcoded to 1 but instead derived from the singleton's name so that it's different for each one and they end up on different nodes.

**Comment by gregor-rayman** [comment]
Created pull request #38 for series/2.x  and #39 for series/1.x
