### ISSUE TITLE
Add possibility to broadcast a message to all pods

### ISSUE THREAD

**Issue by gregor-rayman** [devsisters/shardcake#31]
It would be practical to have the ability to broadcast a message to all pods. It could be a fire and forget messages without an enitityId.

**Comment by ghostdogpr** [comment]
A message to whom (like, who's going to receive the message)? All currently active entities?

**Comment by gregor-rayman** [comment]
A message to the pods, not to the entities. A broadcast receiver would register on the pod, similar to the entity type, with the difference that there would be only a single instance of every broadcast type per pod and the message would be delivered to the receivers on all pods.

My use case is a replacement of Akka cluster, which we use to coordinate instances of our application cluster. Sometimes we need to broadcast messages to all nodes of the cluster. I know this is not sharding, but the existing functionality of Shardcake seems to me to be pretty close, and I hope the needed changes would be small.

I don't know the internals well enough to be able to implement this enhancement (yet). So far I have experimented a bit with the following approaches:

* adding `BinaryBroadcast` similar to `BinaryMessage` withtout the `entrityId` and the corresponding methods - but this lead to quite many changes
* changing the `BinaryMessage` to use `entityIdOpt: Option[String]` instead of `entityId: String` - but this type change also lead to quite many changes 
* using `entityId = null` internally (I know it is ugly) - here I have not yet finished tinkering
* changing the behavior for a new type of "stateless" and mute (not replying) broadcast entities, where despite them having ids and so not being singletons, they would live on all pods instead of just one shard. Their ids would represent something like broadcast topics. - I have not yet started with this yet.

I like the first approach best, because is clearly separates the entities from the broadcast receivers, but it seems to be the biggest change. The 2nd and 3rd approaches try to piggyback on what is already there, but are not so clear. The last approach came last to my mind, but I think it might be require the least changes.

I would be grateful for any guidance.

**Comment by gregor-rayman** [comment]
I have tried the 4th approach where the broadcast "entities" represent topics on all pods. Suspiciously few changes were needed. I have created a draft pull request as a base for discussion whether this approach makes sense.

**Comment by ghostdogpr** [comment]
I like the concept, we actually have something similar where we need to refresh a cache on all pods, currently we are using `Sharding#getPods` but then we have a dedicated RPC for that call, we use shardcake only to get the addresses of all pods.

Your approach seems interesting, will comment on the PR directly.

**Comment by gregor-rayman** [comment]
The local cache refreshing is also one of our use cases :)

**Comment by ghostdogpr** [comment]
Closed by https://github.com/devsisters/shardcake/pull/32
