### ISSUE TITLE
Why GrpcShardingService.layer returns Unit, it breaks type safe

### ISSUE THREAD

**Issue by liewhite** [devsisters/shardcake#57]
Missing GrpcShardingService.live provide will cause exception at runtime

**Comment by ghostdogpr** [comment]
This is a normal pattern with ZIO 2: the `provide` macro will warn you when you provide layers that are not used, but layers that return `Unit` are accepted. The service itself it not used by anything so we don't need to return it.

**Comment by liewhite** [comment]
Tks for your explanation, close the issue.
