### ISSUE TITLE
Delivery guarantees

### ISSUE THREAD

**Issue by mykytamykhailenko** [devsisters/shardcake#63]
Hi, could you tell which delivery guarantees the Shardcake offers?

**Comment by mykytamykhailenko** [comment]
Also, could you tell what happens with the stream created by calling `sendStream`, when the shard on the other end gets 
reassigned?

**Comment by ghostdogpr** [comment]
At most once, similar to Akka.

About sendStream, this is a good question. I haven't handled that part yet but that is definitely something that I need to care about.
