### ISSUE TITLE
[Feature Request] Passivation

### ISSUE THREAD

**Issue by AppleKid7** [devsisters/shardcake#65]
After talking to a colleague who has a lot of experience with Akka clustering, it seems this feature would be well-received by those looking for Akka clustering alternatives. In Akka, passivation works with persistent entities: if an entity is not being used, it can be stopped to reduce memory consumption. Looking through the documentation, it could be done by:

* Setting a timeout on receiving messages (`context.setReceiveTimeout` in Akka)
* Automatically through a config by providing passivation strategy options (e.g. idle entity passivation, limits on the active number of entities, etc)

I don't know if there's an implementation in the works for this, but in case there isn't but there is some interest for it, I'd be happy to take a crack at it.

**Comment by dispalt** [comment]
I think it exists as https://github.com/devsisters/shardcake/blob/09882f037ea7e028a25b1b9213a14eb1845a5656/vuepress/docs/docs/config.md?plain=1#L26

**Comment by ghostdogpr** [comment]
Yeah, @dispalt is correct, you can set the equivalent of `receiveTimeout` with `entityMaxIdleTime`
