### ISSUE TITLE
When to release newer version, which supports zio-grpc 0.6.0-rc5

### ISSUE THREAD

**Issue by BaekGeunYoung** [devsisters/shardcake#70]
I'm trying to migrate my akka-cluster dependency into shardcake.
The latest version of shardcake is 2.0.6, which depends on zio-grpc `0.6.0-rc1`.
But as you know, breaking change occurred between `0.6.0-rc1` and latest version (`0.6.0-rc5`). And I saw the PR which handles this change. (https://github.com/devsisters/shardcake/pull/69)
I want to apply this update to my project. When is the newer version supposed to be released?

**Comment by ghostdogpr** [comment]
I was planning to release once zio-grpc is released officially. But in the meantime you can use the latest snapshot of shardcake which is using RC5. The snapshot number is available in the README, the last one is `2.0.6+6-8cbf54b8-SNAPSHOT` (see also https://s01.oss.sonatype.org/content/repositories/snapshots/com/devsisters/shardcake-core_2.13/)

**Comment by BaekGeunYoung** [comment]
alright. Thank you!
