### ISSUE TITLE
[Feature Request] Proxy only mode

### ISSUE THREAD

**Issue by BaekGeunYoung** [devsisters/shardcake#79]
Hi, I wanna run some nodes as proxy only mode. A node running as proxy mode does not host any entities, and can only send messages to entities hosted in other nodes.

**Comment by ghostdogpr** [comment]
You can already do that, simply by not calling `register` on those nodes.

**Comment by BaekGeunYoung** [comment]
Oh, should I call `registerEntity` only?

**Comment by ghostdogpr** [comment]
No, just `messenger` and you can send messages with it.
