### ISSUE TITLE
[Feature Request] resume failed singleton job

### ISSUE THREAD

**Issue by BaekGeunYoung** [devsisters/shardcake#95]
Is there some way to restart a died singleton job?
It would be great if there is some option that determines whether to restart or not in `registerSingleton` function, or some api like `restartSingleton` which can restart died job manually.

**Comment by ghostdogpr** [comment]
I think it's simpler if it's handled by the user. When you register a singleton, you can decide if you want to catch `Die` errors or not by adding the appropriate error handling in the `run` method.
